import '@/global.css'
import React, { ReactNode } from 'react'
import StyledComponentsRegistry from '../lib/AntdRegistry'

export const metadata = {
	description: 'Generated by create next app',
	title: 'Create Next App',
};

export interface Props {
	children: ReactNode
}

export default ({ children }: Props) => (
	<html>
		<body>
			<StyledComponentsRegistry>
				{children}
			</StyledComponentsRegistry>
		</body>
	</html>
)
